name: keep-db-alive
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          curl --request GET \
          --url 'https://stack-ranger.romagnoli.me/?role=Senior+Software+Engineer&search=skill'
