name: fetch-jobs-cron
on:
#  schedule:
#    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route to trigger fetch jobs
        run: |
          curl --request GET \
          --url 'https://stack-ranger.romagnoli.me/api/microservice' \
          --header 'Authorization: ${{ secrets.AUTHORIZATION_HEADER }}' 
